name: SonarCloud
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Instalar el scanner de SonarCloud
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Iniciar análisis
        env:
          SONAR_TOKEN: "cf7013ea92fe5a7c985bc591b5260f7a7053c3bb"
        run: >
          dotnet-sonarscanner begin
          /k:"andrewstyle22" /o:"andrewstyle22"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.token="cf7013ea92fe5a7c985bc591b5260f7a7053c3bb"
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - run: dotnet build --no-incremental

      - name: Ejecutar tests con cobertura
        run: >
          dotnet test
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover
          /p:CoverletOutput=./coverage.opencover.xml

      - name: Terminar análisis
        env:
          SONAR_TOKEN: "cf7013ea92fe5a7c985bc591b5260f7a7053c3bb"
        run: dotnet-sonarscanner end /d:sonar.token="cf7013ea92fe5a7c985bc591b5260f7a7053c3bb"
